logto-io/swift

- .github/workflows/main.yml
Init basic Swift CI.
@logto-io/eng
> chore: init main workflow

- .github/pull_request_template.md
- Sources/Logto/Types/IdTokenClaims.swift
1. add `IDTokenClaims` type
2. add PR template
since API response types will come with API functions, the only type we need to define in this PR is ID Token Claims.
@logto-io/eng
> feat: `IDTokenClaims` type

- .github/workflows/main.yml
- BuildTools/Empty.swift
- BuildTools/Package.swift
- Package.swift
- Sources/Logto/Logto.swift
- Sources/Logto/LogtoUtilities.swift
- Sources/Logto/Types/IdTokenClaims.swift
- Tests/LogtoTests/LogtoTests.swift
- Tests/LogtoTests/LogtoUtilitiesTests.swift
- implement `generateCodeVerifier()`
- add SwiftFormat in CI
UT
@logto-io/eng
> feat: `generateCodeVerifier()`

- .github/workflows/add-labels.yml
add labels workflow
N/A
@logto-io/eng
> ci: add labels

- .github/pull_request_template.md
- Sources/Logto/Extensions/Data.swift
- Sources/Logto/Extensions/String.swift
- Sources/Logto/LogtoUtilities.swift
- Tests/LogtoTests/LogtoUtilitiesTests.swift
- implement `generateState()`
- implement `generateCodeChallenge()` (resolves LOG-953)
- generate URL safe strings for Code Verifier and State
UT
@logto-io/eng
> feat: `generateState()` and `generateChallenge()`

- Sources/Logto/Extensions/Collection.swift
- Sources/Logto/Extensions/String.swift
- Sources/Logto/LogtoUtilities.swift
- Sources/Logto/Types/IdTokenClaims.swift
- Sources/Logto/Types/LogtoErrors.swift
- Tests/LogtoTests/LogtoUtilitiesTests.swift
- implement `decodeIdToken()`
UT
@logto-io/eng
> feat: `decodeIdToken()`

- Package.resolved
- Package.swift
- Sources/Logto/Extensions/SignatureAlgorithm.swift
- Sources/Logto/LogtoUtilities.swift
- Sources/Logto/Types/JWT.swift
- Sources/Logto/Types/LogtoErrors.swift
- Tests/LogtoTests/LogtoUtilitiesTests.swift
implement `verifyIdToken()` following SDK convention.
note i edited the function signature in order to explicitly passing "RSA public keys" instead of the JWK set since there are too many encryption methods and some of them do not support verification. also left a comment in Notion.
```swift
static func verifyIdToken(
_ idToken: String,
issuer: String,
clientId: String,
publicKeys: [RSAPublicKey],
// ...
)
```
UT
@logto-io/eng
> feat: `verifyIdToken()`

- Sources/Logto/Core/LogtoCore.swift
- Sources/Logto/Types/LogtoErrors.swift
- Sources/Logto/Types/ValueOrArray.swift
- Tests/LogtoTests/LogtoCoreTests.swift
implement `generateSignInUrl()` according to SDK convention
UT
@logto-io/eng
> feat: `generateSignInUrl()`

- .swiftformat
- Sources/Logto/Core/LogtoCore.swift
- Sources/Logto/Extensions/Data.swift
- Tests/LogtoTests/LogtoCoreTests.swift
- Tests/LogtoTests/LogtoUtilitiesTests.swift
add basic SwiftFormat config, and run auto-fix over the project.
UT
@logto-io/eng
> chore: add SwiftFormat config

- Sources/Logto/Core/LogtoCore+Fetch.swift
- Sources/Logto/Types/LogtoErrors.swift
- Sources/Logto/Utilities/LogtoUtilities+IdToken.swift
- Sources/Logto/Utilities/Utilities.swift
- Tests/LogtoTests/LogtoCore+FetchTests.swift
- implement simple http get method with json decoder
- implement `fetchOidcConfig()`
UT
@logto-io/eng
> feat: `fetchOidcConfig()`

- Sources/Logto/Core/LogtoCore.swift
- Tests/LogtoTests/LogtoCoreTests+GenerateSignOutUri.swift
implement `generateSignOutUri()`
UT
@logto-io/eng
> feat: `generateSignOutUri()`

- Sources/Logto/Core/LogtoCore.swift
- Sources/Logto/Types/LogtoErrors.swift
- Tests/LogtoTests/LogtoCoreTests.swift
implement `verifyAndParseSignInCallbackUri()`
UT
@logto-io/eng
> feat: `verifyAndParseSignInCallbackUri()`

- Tests/LogtoTests/LogtoCoreTests+Generate.swift
`testgenerateSignInUri` -> `testGenerateSignInUri`
N/A
@logto-io/eng
> chore: fix typo

- Sources/Logto/Core/LogtoCore+Fetch.swift
- Sources/Logto/Utilities/Utilities.swift
- Tests/LogtoTests/LogtoCoreTests+Fetch.swift
- Tests/LogtoTests/URLSessionMock.swift
- implement `fetchUserInfo()`
UT
@logto-io/eng
> feat: `fetchUserInfo()`

- Sources/Logto/Core/LogtoCore+Fetch.swift
- Tests/LogtoTests/LogtoCoreTests+Fetch.swift
- implement `fetchTokenByRefreshToken()`
UT
@logto-io/eng
> feat: `fetchTokenByRefreshToken()`

- Sources/Logto/Core/LogtoCore+Revoke.swift
- Sources/Logto/Types/HttpCompletion.swift
- Sources/Logto/Utilities/Utilities.swift
- Tests/LogtoTests/LogtoCoreTests+Revoke.swift
- Tests/LogtoTests/URLSessionMock.swift
- implement `revoke()`
UT
@logto-io/eng
> feat: `revoke()`

- Sources/Logto/Core/LogtoCore+Fetch.swift
- Sources/Logto/Core/LogtoCore.swift
- Sources/LogtoClient/LogtoClient/LogtoClient.swift
- Sources/LogtoClient/Types/AccessToken.swift
- Sources/LogtoClient/Types/LogtoConfig.swift
- init `LogtoClient` class
- change some visibilities to `public`
N/A
@logto-io/eng
> feat: init `LogtoClient`

- .github/pull_request_template.md
Fix typos in pull request template
`bellow` => `below`
`Reviwers` => `Reviewers`
https://linear.app/silverhand/issue/LOG-1408/fix-typo-in-github-pull-request-template
@logto-io/eng
> chore: fix typos in pull request template

- Package.swift
- Sources/Logto/Extensions/URLSession.swift
- Sources/Logto/Protocols/NetworkSession.swift
- Sources/Logto/Types/HttpCompletion.swift
- Sources/Logto/Types/LogtoErrors.swift
- Sources/Logto/Utilities/LogtoRequest.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
- Sources/LogtoClient/LogtoClient/LogtoClient.swift
- Sources/LogtoClient/Types/LogtoClientErrors.swift
- Sources/LogtoClient/Types/LogtoConfig.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClient+SignInTests.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClient.swift
- Tests/LogtoClientTests/Types/LogtoConfigTests.swift
- Tests/LogtoMock/URLSessionMock.swift
- Tests/LogtoTests/LogtoCoreTests+Fetch.swift
- Tests/LogtoTests/LogtoCoreTests+Revoke.swift
- extract `NetworkSessionMock` to shared target for tests
- implement internal method `.fetchOidcConfig()`
UT
@logto-io/eng
> feat(client): fetch OIDC config

- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- Sources/Logto/Core/LogtoCore+Fetch.swift
- Sources/Logto/Core/LogtoCore+Generate.swift
- Sources/Logto/Core/LogtoCore+Verify.swift
- Sources/Logto/Extensions/Dictionary.swift
- Sources/Logto/Extensions/URLSession.swift
- Sources/Logto/Types/LogtoErrors.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
- Sources/LogtoClient/LogtoClient/LogtoClient.swift
- Tests/LogtoTests/LogtoCoreTests+Generate.swift
- Tests/LogtoTests/LogtoCoreTests+Verify.swift
- extract `LogtoSignInSession` out of `LogtoClient`
- fetch token by auth code after successfully signed in
successfully fetch tokens by auth code
@logto-io/eng
> feat: full funcitonal sign in

- Sources/Logto/Core/LogtoCore+Fetch.swift
for better understanding
N/A
@logto-io/eng
> refactor: add comment for `userinfoEndpoint`

- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+PersistStorage.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
- Sources/LogtoClient/LogtoClient/LogtoClient.swift
remove keychain storage for access token per discussion
@logto-io/eng
> refactor: remove access token persist storage

- Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+Fetch.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignOut.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
> test(client): add test cases for `.signIn()`

- Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+Fetch.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignOut.swift
- Tests/LogtoMock/NetworkSessionMock.swift
> test(client): add test cases for `.fetchUserInfo()`

- Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
> test(client): add test cases for `.getAccessToken()`

- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
add test cases for:
- `.isAuthenticated`
- `.getIdTokenClaims()`
- `usingPersistStorage`
the PR itself
@logto-io/eng
> test(client): add test cases

- Sources/Logto/Utilities/LogtoUtilities.swift
- Tests/LogtoClientTests/Types/LogtoConfigTests.swift
- Tests/LogtoTests/LogtoCoreTests+Generate.swift
- Tests/LogtoTests/LogtoUtilitiesTests.swift
- remove `.sort()` in `.withReservedScopes()` per discussion
- refactor URL query unit tests
UT
@logto-io/eng
> refactor(core): remove `.sort()` in `.withReservedScopes()`

- .github/workflows/main.yml
enable codecov report
LOG-1393
@logto-io/eng
> test(coverage): enable codecov report

- Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
add explicit `self` usage to avoid warning
UT
@logto-io/eng
> refactor: update `self` usage

- .swiftpm/xcode/xcshareddata/xcschemes/Logto SDK-Package.xcscheme
- Package.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
- Sources/LogtoClient/LogtoClient/LogtoClient.swift
- Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
- Sources/LogtoSocialPluginWeb/LogtoSocialPluginWeb.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
- extract plugin protocol for further integration of 3rd party native SDKs
- implement `LogtoSocialPluginWeb` for OAuth social identity providers
tested in demo - GitHub social works
@logto-io/eng
> refactor(client): social plugin

- .github/workflows/main.yml
- .swiftpm/xcode/xcshareddata/xcschemes/Logto SDK-Package.xcscheme
- Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- Demos/SwiftUI Demo/SwiftUI Demo/SwiftUI_DemoApp.swift
- Demos/SwiftUI Demo/SwiftUI-Demo-Info.plist
- Package.swift
- Sources/LogtoClient/LogtoClient/LogtoClient.swift
- Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
- Sources/LogtoSocialPlugin/LogtoSocialPluginError.swift
- Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
- Sources/LogtoSocialPluginWeb/LogtoSocialPluginWeb.swift
implement Alipay social plugin
note we are using a separate repo https://github.com/logto-io/social-sdks for maintaining "edited official SDKs" (Alipay doesn't have an official xcframework) to leverage [SPM binary dependency](https://github.com/apple/swift-evolution/blob/main/proposals/0272-swiftpm-binary-dependencies.md). 
to-do: LOG-2084 to use global scheme for 3rd party app to go back
LOG-2038
https://user-images.githubusercontent.com/14722250/161216194-7ea2aebf-0a63-4729-b277-8d280a9f7311.MP4
and it works!
@logto-io/eng
> feat(client): Alipay social plugin

- .github/workflows/main.yml
- generate-codecov-json.js
- use `xcpretty` for now since `xcbeautify` takes too long to install in CI
- fix pipeline issue
- use CI compatible Xcode destination
CI
@logto-io/eng
> ci: fix build script

- .swiftpm/xcode/xcshareddata/xcschemes/Logto SDK-Package.xcscheme
- Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- Demos/SwiftUI Demo/SwiftUI Demo/SwiftUI Demo.entitlements
- Demos/SwiftUI Demo/SwiftUI-Demo-Info.plist
- Package.swift
- Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
- Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
implement Wechat social plugin
LOG-2090
https://user-images.githubusercontent.com/14722250/161926549-d30ca68c-1a93-4d7d-9904-8d3d93c558bb.mov
got correct callback URL
@logto-io/eng
> feat(client): Wechat social plugin

- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- Sources/Logto/Core/LogtoCore+Fetch.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
- refactor `LogtoAuthSession` using async
- validate ID Token after successfully signed in
LOG-2040
UT + Demo sign in
@logto-io/eng
> refactor: validate ID Token after signed in

- .github/workflows/main.yml
- BuildTools/Package.resolved
- restore lint step 
- add version number to cache key to enable a new cache policy and use `actions/cache@v3`
- use cached SwiftFormat executable when possible
- commit `BuildTools/Package.resolved` to cache SwiftFormat build folder
CI
https://github.com/logto-io/swift/runs/5992750230?check_suite_focus=true
https://github.com/logto-io/swift/runs/5993008251?check_suite_focus=true
@logto-io/eng
> ci: update main workflow

- Sources/Logto/Extensions/URLSession.swift
- Tests/LogtoTests/URLSessionTests.swift
add test cases for `URLSession` extension
LOG-1527
@logto-io/eng
> test(core): add `URLSession` test cases

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
- Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
add `isAvailable` for social plugins and filter before passing to webview
LOG-2175
UT later
@logto-io/eng
> refactor(plugin): add `isAvailable`

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
return real `postMessage()` method
pending test after simulator issue has been fixed in the next PR
@logto-io/eng
> fix(client): update `getPostMessage()`

- Package.swift
use new technology to support arm64 simulator
build & run ok
@logto-io/eng
> refactor(client): support arm64 simulator

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthSessionTests.swift
didn't add tests for some lines with low ROI
LOG-1525
UT
@logto-io/eng
> test(client): add LogtoWebViewAuthSession tests

- Sources/Logto/Core/LogtoCore+Generate.swift
- Tests/LogtoTests/LogtoCoreTests+Generate.swift
use `consent` as prompt value per OIDC specs and discussion
LOG-2184
UT
@logto-io/eng
> refactor(core): login -> consent

- LICENSE.md
add MIT license
N/A
@logto-io/eng
> chore: add LICENSE

- Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
> test(client): add tests for `LogtoAuthSession`

- Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
> test(client): add tests for `LogtoClient`

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
> test(client): add tests for `LogtoWebViewAuthViewController`

- .github/workflows/main.yml
- .swiftpm/xcode/xcshareddata/xcschemes/LogtoSDK-Package.xcscheme
- Package.swift
- Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
- Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
correct target type and use conditional compilation to enable SwiftPM build again
@logto-io/eng
> fix: SwiftPM build

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
bind wkwebview postMessage method this context
https://stackoverflow.com/questions/57367319/using-javascript-with-wkwebview-error-on-usermessagehandler
test locally on simulator
@logto-io/eng
> feat(ios-sdk): bind wkwebview postMessage method this

- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
- Sources/LogtoSocialPlugin/LogtoSocialPluginError.swift
- Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
- Sources/LogtoSocialPluginWeb/LogtoSocialPluginWeb.swift
- Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
align social errors with [convention](https://www.notion.so/silverhand/Social-Errors-94f8499b728947fa8309267f69a7d7c5)
UT
@logto-io/eng
> refactor(social): align social errors

- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- Sources/Logto/Core/LogtoCore+Fetch.swift
- Sources/Logto/Types/IdTokenClaims.swift
- Sources/Logto/Types/JWT.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
- Sources/LogtoClient/LogtoClient/LogtoClient.swift
- Sources/LogtoClient/Types/AccessToken.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignOut.swift
- add public props/funcs docs for LogtoClient.
- update some function signatures to a more reasonable state.
looks good in quick help
@logto-io/eng
> docs: add LogtoClient docs

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController+WKNavigationDelegate.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController+WKScriptMessageHandler.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthSessionTests.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
auth session will finish with error when user manually dismisses the sign in sheet
LOG-2194
@logto-io/eng
> refactor(client): complete with error when manually dismissal

- Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
since it may need more time in slow machines
CI
@logto-io/eng
> refactor(test): increase post message timeout

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
per discussion align WebView variable "callbackLink" key and value
@logto-io/eng
> refactor(client): align WebView variable

- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
- Sources/LogtoClient/LogtoClient/LogtoClient.swift
- Sources/LogtoClient/Types/LogtoConfig.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
- Tests/LogtoClientTests/Types/LogtoConfigTests.swift
to reduct friction when getting started with Logto
LOG-2251
UT
@logto-io/eng
> refactor(client): `clientId` -> `appId`

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- let WebView to handle safe area
- viewWillDisappear -> viewDidDisappear to prevent accidentally trigger
phone
@logto-io/eng
> fix: webview issues

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
- Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
- Sources/LogtoSocialPluginWeb/LogtoSocialPluginWeb.swift
- Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
rename `connectorId` -> `supportedConnector` to align core update
UT
@logto-io/eng
> refactor: `connectorId` -> `supportedConnector`

- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController+WKNavigationDelegate.swift
- Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
- Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
to make it more user friendly, resolves LOG-3404
- loading: indicator shows
- loaded: indicator hides, interaction works
> feat(client): show loading indicator in webview

- .github/pull_request_template.md
use default community health files from [logto-io/.github](https://github.com/logto-io/.github).
N/A
> chore: use default community health files

- Sources/Logto/Protocols/UserInfoProtocol.swift
Move file to the expected location and fix typo
/
> refactor: fix typo

- Sources/Logto/Core/LogtoCore+Fetch.swift
- Sources/Logto/Protocols/UserInfoProtocol.swift
- Sources/Logto/Types/IdTokenClaims.swift
fix types, will update the docs as well
UT
> fix: user info types

- Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
- README.md
- Sources/Logto/Core/LogtoCore+Fetch.swift
- Sources/Logto/Protocols/UserInfoProtocol.swift
- Sources/Logto/Types/IdTokenClaims.swift
- Sources/Logto/Types/ReservedResource.swift
- Sources/Logto/Types/UserScope.swift
- Sources/Logto/Utilities/LogtoUtilities.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
- Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
- Sources/LogtoClient/Types/LogtoConfig.swift
- Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
- Tests/LogtoTests/LogtoUtilitiesTests.swift
- add enums and organization-related methods. resolves LOG-7575.
- update sample accordingly
> feat: support organizations
